export const ADD_USER = 'ADD_USER';
export const LOAD_ENGINEERS_SUCCESS = 'LOAD_ENGINEERS_SUCCESS';
export const RATE_ENGINEER_SUCCESS = 'RATE_ENGINEER_SUCCESS';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
