export const AUTH_USER = 'AUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const ADD_USER = 'ADD_USER'
export const GET_ENGINEERS = 'GET_ENGINEERS'
export const GET_SINGLE_ENGINEER = 'GET_SINGLE_ENGINEER'
